- components/blackmagic/CMakeLists.txt
As of 2022-07-22, this is now required.
Signed-off-by: Sean Cross <sean@xobs.io>
> cmake: add esp_wifi to required lists

- main/adc.c
The voltage scaling wasn't properly taking into account attenuation.
Scale by an additional 4/3 to compensate for the 2.5 dB attenuation.
Signed-off-by: Sean Cross <sean@xobs.io>
> adc: fix voltage scaling

- components/blackmagic/general.h
- components/blackmagic/jtagtap.c
- components/blackmagic/swdptap-gpio.c
- components/blackmagic/swdptap-ulp.c
- main/gdb_if.c
- main/http.c
- main/include/platform.h
- main/platform.c
Fix the following issues:
* The UART was incorrect, resulting in a crash when the built-in serial debug UART was disabled
* BMP has increased its stack usage, causing a stack overflow
> Bmp stack uart fixes

- main/include/platform.h
An upstream change broke opencm3 to the point where it no longer builds.
Signed-off-by: Sean Cross <sean@xobs.io>
> components: update blackmagic to fix opencm3

- components/blackmagic/CMakeLists.txt
ESP now requires the esp_partition component. This fixes the build.
> esp-idf: add partition requirements

- .github/workflows/build-nightly-blackmagic.yml
This will allow us to ensure we can merge history. This fixes the nightly build.
> github: unshallow the blackmagic port to merge history

- main/include/platform.h
This flag has appeared and indicates whether or not debug is enabled. Add this flag to the platform header file to fix compiling with the latest nightly bmp.
> platform: add `debug_bmp` bool

- main/gdb_main.c
> blackmagic: add pbuf_size to gdb_main

- main/uart.c
Ideally this would go to a different channel, but this at least fixes the build.
> uart: implement debug_serial_send_stdout

- README.md
This updates several links to the Black Magic Probe github repository, as well as their website.
> README: Fix outdated links for BMD Project

- main/platform.c
Booleans have been added a few place. Update our platform file to match, and pull the new version of upstream.
> upstream: fix bools

- main/platform.c
It's unclear why this suddenly cropped up.
> platform: fix printf typecast format error

- main/platform.c
Previously, `platform_set_baud()` would store the new baudrate, then set the rate to 115200. Actually set the baudrate now.
> Have platform_set_baud() actually set the baudrate

- main/http_api.c
Upstream changed how target info is accessed. We must now import `target_private.h` and access the fields directly.
> http: rework target info to support upstream changes

- main/uart.c
> The allocated stack size of 2048 for xTaskCreate is too small.

- components/blackmagic/usb.h
- main/http.c
- main/include/platform.h
`command.c` now requires `usb.h` to exist, as well as a dummy `TRACE_ENDPOINT` value for printing.
This value is not used except to print a message.
> usb.h: add file to fix nightly build

- main/http_api.c
The buffer will be filled with a long SSID or a long hostname.
> http-api: increase buffer for status page

- .github/workflows/build-and-upload.yml
Github has broken v1 and v2. Jump straight to v4 to see if that fixes the build.
> github: replace upload-artifact with v4

- components/blackmagic/general.h
- main/gdb_main.c
- main/gdb_main_farpatch.h
- main/include/platform.h
Upstream now requires us to provide a packet buffer in an external function rather than passing it through `gdb_main()`.
> blackmagic: add new packet buffer function

- main/http.c
- main/include/platform.h
The two http buffer variables were changed in [9846584defbb87ebbf64582ec0ad3bff848ca96f ](https://github.com/espressif/esp-idf/commit/9846584defbb87ebbf64582ec0ad3bff848ca96f) resulting in nightly breakage. Follow this rename.
> esp-idf: follow rename of http buffer variables

- main/platform.c
The prototype was missing the argument. This is now a hard error. Correct the prototype by inserting the argument.
> gdb_net_task: correct function prototype
